### ISSUE TITLE
cppcheck: Failed to load library configuration file 'std.cfg'

### ISSUE THREAD

**Issue by harshn05** [brechtsanders/winlibs_mingw#198]
_cppcheck test.cpp_

**cppcheck: Failed to load library configuration file 'std.cfg'. File not found**
Failed to load std.cfg. Your Cppcheck installation is broken, please re-install. The Cppcheck binary was compiled with FILESDIR set to "R:/winlibs64ucrt_stage/inst_cppcheck-2.13.0/share/Cppcheck" and will therefore search for std.cfg in R:/winlibs64ucrt_stage/inst_cppcheck-2.13.0/share/Cppcheck/cfg.

**Comment by brechtsanders** [comment]
Hmm, looks like it's not very relocatable. Maybe it needs some code changes to look in a location relative to the `.exe` file...

**Comment by brechtsanders** [comment]
The new release I just published use Cppcheck version 2.14.0 instead of 2.13.0.
Can you check if this solves the issue for you?

**Comment by lzralbu** [comment]
Just found this issue as I'm having the same problem. It still doesn't work with version 2.14.0.

I ran the following commands from cmd:

input: `cppcheck src\level.c`
output: `cppcheck: Failed to load library configuration file 'std.cfg'. File not found
Failed to load std.cfg. Your Cppcheck installation is broken, please re-install. The Cppcheck binary was compiled with FILESDIR set to "R:/winlibs64ucrt_stage/inst_cppcheck-2.14.0/share/Cppcheck" and will therefore search for std.cfg in R:/winlibs64ucrt_stage/inst_cppcheck-2.14.0/share/Cppcheck/cfg.`

input: `cppcheck --library=C:\build-tools\winlibs-x86_64-posix-seh-gcc-13.2.0-mingw-w64ucrt-11.0.1-r8\mingw64\share\Cppcheck\cfg\std.cfg src\level.c`
output: `cppcheck: Failed to load library configuration file 'std.cfg'. File not found
Failed to load std.cfg. Your Cppcheck installation is broken, please re-install. The Cppcheck binary was compiled with FILESDIR set to "R:/winlibs64ucrt_stage/inst_cppcheck-2.14.0/share/Cppcheck" and will therefore search for std.cfg in R:/winlibs64ucrt_stage/inst_cppcheck-2.14.0/share/Cppcheck/cfg.`

**Comment by brechtsanders** [comment]
Maybe you should raise a ticket with the developer(s) os cppcheck to ask if it's possible to make the program relocatable (i.e. make it look for files like `std.cfg` relative to the locatio of `cppcheck.exe`).

**Comment by ghost** [comment]
Please have a look at the MSYS2 package for `cppcheck`:

https://packages.msys2.org/package/mingw-w64-x86_64-cppcheck?repo=mingw64

Well, I think the program is relocatable.

**Comment by brechtsanders** [comment]
If you're referring to https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-cppcheck/002-cppcheck-2.2-change-cfg-path.patch then it looks like there is an actual issue in the cppcheck code which points to the wrong relative path.

I will make the same modification in my [build recipe for cppcheck](https://github.com/brechtsanders/winlibs_recipes/blob/main/recipes/cppcheck.winlib).
