### ISSUE TITLE
GDB readline duplicates input sent from window terminal

### ISSUE THREAD

**Issue by liuyug** [brechtsanders/winlibs_mingw#252]
Use gdb with packages:
winlibs-i686-posix-dwarf-gcc-14.2.0-llvm-19.1.7-mingw-w64ucrt-12.0.0-r3.7z  or
winlibs-x86_64-posix-seh-gcc-14.2.0-llvm-19.1.7-mingw-w64ucrt-12.0.0-r3.7z

Input command in gdb console, such as "?<enter>"

terminal output:

```
(gdb) ?
?
Undefined command: "".  Try "help".
(gdb)

Undefined command: "".  Try "help".
```

```
(gdb) show configuration
show configuration
This GDB was configured as follows:
   configure --host=i686-w64-mingw32 --target=i686-w64-mingw32
             --with-auto-load-dir=$debugdir:$datadir/auto-load
             --with-auto-load-safe-path=$debugdir:$datadir/auto-load
             --with-expat
             --with-gdb-datadir=/R/winlibs_staging_ucrt32/inst_gdb-16.2/share/gdb/share/gdb (relocatable)
             --with-jit-reader-dir=/R/winlibs_staging_ucrt32/inst_gdb-16.2/share/gdb/lib/gdb (relocatable)
             --without-libunwind-ia64
             --with-lzma
             --without-babeltrace
             --without-intel-pt
             --with-xxhash
             --with-python=C:/Prog/winlibs_staging_ucrt/custombuilt32/share/python
             --with-python-libdir=/c/Prog/winlibs_staging_ucrt/custombuilt32/share/python/lib
             --without-debuginfod
             --with-curses
             --without-guile
             --without-amd-dbgapi
             --enable-source-highlight
             --enable-threading
             --enable-tui
             --with-system-readline
             --with-separate-debug-dir=/R/winlibs_staging_ucrt32/inst_gdb-16.2/share/gdb/lib/debug (relocatable)
             --with-system-gdbinit=/R/winlibs_staging_ucrt32/inst_gdb-16.2/share/gdb/share/gdb/gdbinit (relocatable)

("Relocatable" means the directory can be moved with the GDB installation
tree, and GDB will still find it.)

GNU Readline library version: 8.2       (system)
(gdb)
```
"--with-system-readline" cause the bug.

**Comment by ssbssa** [comment]
This might be the issue mentioned here:
https://sourceware.org/pipermail/gdb-patches/2024-November/212892.html

**Comment by brechtsanders** [comment]
> "--with-system-readline" cause the bug.

If that triggers the bug, isn't there a patch for readline than I can apply?

My goal is to use as much shared libraries as possible to keep the executables small and fast. That is why my build always prefer "system" libraries while having also build these libraries from source.

> This might be the issue mentioned here:
> https://sourceware.org/pipermail/gdb-patches/2024-November/212892.html

I don't see the link with the Ctrl-D issue. Why do you think it's related?

So for I wasn't able to reproduce your issue.
From which shell were you running it (MSYS2, Command Prompt, PowerShell, ...) to get duplicate output?

**Comment by ssbssa** [comment]
> I don't see the link with the Ctrl-D issue. Why do you think it's related?

I'm not completely sure, but it was introduced with readline 8.2, and it's about weird additional output, that's why I mentioned it.

If it is related, a readline patch is linked in there:
https://lists.gnu.org/archive/html/bug-readline/2024-10/msg00014.html

**Comment by liuyug** [comment]
run "gdb.exe" in cmd or powershell console in Windows11 and then the issue will catch it. 
I am only gdb user and not konw about patch... 

I find another gdb from https://github.com/ssbssa/gdb. it work!

**Comment by chqN** [comment]
I think I have the same issue. I installed my programs from GCC 14.2.0 full package, Win64, 7-Zip.
I'm in Windows 10 and since the start I always had this problem.
If it's any help, here's a video demonstration. 

https://github.com/user-attachments/assets/21aedba6-39a7-4c1c-9e89-242d0016a0f6

**Comment by brechtsanders** [comment]
I released a GCC 15.1.0 build (with GDB 16.3) just yesterday. Can you please check if the issue is still present when using that?

**Comment by chqN** [comment]
For me, the issue is still there. It behaves the same way.
Edit: Just in case, I also checked the MSVCRT runtime version. It's the same as well.

![Image](https://github.com/user-attachments/assets/1b90e3c5-257f-4fe8-8d07-4438f3103faa)

**Comment by liuyug** [comment]
![Image](https://github.com/user-attachments/assets/6ecce2ad-2c4c-4fdb-89f5-3107802318cf)

The issue is still present.

**Comment by ccx004B** [comment]
I too have the same problem with GDB 16.3 on Windows 10 22H2 run from command prompt and PowerShell. However, GDB version 15.1 on the same computer doesn't do this. It is a fresh install of winlibs-x86_64-posix-seh-gcc-15.1.0-mingw-w64msvcrt-12.0.0-r1.zip, Not a big issue since I can use the older version perfectly happily.

EDIT: Sorry, I should have checked more carefully. The older version doesn't work. Debugging the simple example program does this:

`(gdb) run
Starting program: C:\.........\test.exe
[New Thread 11160.0x3940]
Python Exception <class 'AttributeError'>: 'gdb.Progspace' object has no attribute 'missing_file_handlers'
Python Exception <class 'AttributeError'>: 'gdb.Progspace' object has no attribute 'missing_file_handlers'
Python Exception <class 'AttributeError'>: 'gdb.Progspace' object has no attribute 'missing_file_handlers'
Python Exception <class 'AttributeError'>: 'gdb.Progspace' object has no attribute 'missing_file_handlers'

Thread 1 hit Breakpoint 1, main () at test.c:5
5         printf("Hello World!\n");
(gdb) s
printf (__format=0x7ff6a935b050 <incomplete sequence \145\154\154\157\040\127\157\162\154\144\041\012>)
    at C:/Local/mingw64/x86_64-w64-mingw32/include/stdio.h:382`

even though, in my entire life I have never used python, am not using it now and will never use it in the future if I can avoid it. Ah well, I should have expected something like this as I am mixing an executable from an earlier version.

**Comment by brechtsanders** [comment]
I just noticed a new readline version was released.
I will try to find the time to build gdb with it so I can check if the issue is resolved with the new readline.

**Comment by brechtsanders** [comment]
Building GDB with `--without-system-readline` seems to fix the issue for me.
Apparently GDB has issues with the existing readline, even the latest version...

**Comment by brechtsanders** [comment]
Please check if the GDB issue is now resolved in
https://github.com/brechtsanders/winlibs_mingw/releases/tag/15.1.0posix-13.0.0-msvcrt-r3
or
https://github.com/brechtsanders/winlibs_mingw/releases/tag/15.1.0posix-13.0.0-ucrt-r3

**Comment by ccx004B** [comment]
Hi Brecht,

 

I downloaded it and tried it but it still shows the same bug. However, it also shows that system readline is still being used:

 

c:\Local\mingw64\bin\gdb

GNU gdb (GDB for MinGW-W64 x86_64, built by Brecht Sanders, r3) 16.3

Copyright (C) 2024 Free Software Foundation, Inc.

License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software: you are free to change and redistribute it.

There is NO WARRANTY, to the extent permitted by law.

Type "show copying" and "show warranty" for details.

This GDB was configured as "x86_64-w64-mingw32".

Type "show configuration" for configuration details.

For bug reporting instructions, please see:

<https://www.gnu.org/software/gdb/bugs/>.

Find the GDB manual and other documentation resources online at:

    <http://www.gnu.org/software/gdb/documentation/>.

 

For help, type "help".

Type "apropos word" to search for commands related to "word".

(gdb) show configuration

show configuration

This GDB was configured as follows:

   configure --host=x86_64-w64-mingw32 --target=x86_64-w64-mingw32

             --with-auto-load-dir=$debugdir:$datadir/auto-load

             --with-auto-load-safe-path=$debugdir:$datadir/auto-load

             --with-expat

             --with-gdb-datadir=/R/winlibs_staging_msvcrt64/inst_gdb-16.3/share/gdb/share/gdb (relocatable)

             --with-jit-reader-dir=/R/winlibs_staging_msvcrt64/inst_gdb-16.3/share/gdb/lib/gdb (relocatable)

             --without-libunwind-ia64

             --with-lzma

             --without-babeltrace

             --without-intel-pt

             --with-xxhash

             --with-python=C:/Prog/winlibs_staging_msvcrt/custombuilt64/share/python

             --with-python-libdir=/c/Prog/winlibs_staging_msvcrt/custombuilt64/share/python/lib

             --without-debuginfod

             --with-curses

             --without-guile

             --without-amd-dbgapi

             --enable-source-highlight

             --enable-threading

             --enable-tui

             --with-system-readline

             --with-separate-debug-dir=/R/winlibs_staging_msvcrt64/inst_gdb-16.3/share/gdb/lib/debug (relocatable)

             --with-system-gdbinit=/R/winlibs_staging_msvcrt64/inst_gdb-16.3/share/gdb/share/gdb/gdbinit (relocatable)

 

("Relocatable" means the directory can be moved with the GDB installation

tree, and GDB will still find it.)

 

GNU Readline library version: 8.3       (system)

(gdb)

 

This GDB was configured as follows:

   configure --host=x86_64-w64-mingw32 --target=x86_64-w64-mingw32

             --with-auto-load-dir=$debugdir:$datadir/auto-load

             --with-auto-load-safe-path=$debugdir:$datadir/auto-load

             --with-expat

             --with-gdb-datadir=/R/winlibs_staging_msvcrt64/inst_gdb-16.3/share/gdb/share/gdb (relocatable)

             --with-jit-reader-dir=/R/winlibs_staging_msvcrt64/inst_gdb-16.3/share/gdb/lib/gdb (relocatable)

             --without-libunwind-ia64

             --with-lzma

             --without-babeltrace

             --without-intel-pt

             --with-xxhash

             --with-python=C:/Prog/winlibs_staging_msvcrt/custombuilt64/share/python

             --with-python-libdir=/c/Prog/winlibs_staging_msvcrt/custombuilt64/share/python/lib

             --without-debuginfod

             --with-curses

             --without-guile

             --without-amd-dbgapi

             --enable-source-highlight

             --enable-threading

             --enable-tui

             --with-system-readline

             --with-separate-debug-dir=/R/winlibs_staging_msvcrt64/inst_gdb-16.3/share/gdb/lib/debug (relocatable)

             --with-system-gdbinit=/R/winlibs_staging_msvcrt64/inst_gdb-16.3/share/gdb/share/gdb/gdbinit (relocatable)

 

("Relocatable" means the directory can be moved with the GDB installation

tree, and GDB will still find it.)

 

GNU Readline library version: 8.3       (system)

(gdb)

 

 

I don’t know why this is happening. You will also see that it has displayed the output from the “show configuration” command twice.

 

Best wishes…

Colin Bruce

**Comment by ccx004B** [comment]
I'm afraid although it says built without  system readline in fact it most definately is built with system readline as can be seen here:
`             --enable-source-highlight
             --enable-threading
             --enable-tui
             --with-system-readline
             --with-separate-debug-dir=/R/winlibs_staging_ucrt64/inst_gdb-16.3/share/gdb/lib/debug (relocatable)
             --with-system-gdbinit=/R/winlibs_staging_ucrt64/inst_gdb-16.3/share/gdb/share/gdb/gdbinit (relocatable)

("Relocatable" means the directory can be moved with the GDB installation
tree, and GDB will still find it.)

GNU Readline library version: 8.3       (system)`

I would build it myself but the source files (both zip and tar.gz versions) only contain a single readme file.

**Comment by brechtsanders** [comment]
Please try again with the latest release at:
https://github.com/brechtsanders/winlibs_mingw/releases/tag/15.1.0posix-13.0.0-ucrt-r4

**Comment by ccx004B** [comment]
Dear Brecht,

 

That’s fixed it.

 

Best wishes….

Colin Bruce

**Comment by liuyug** [comment]
Brecht,

You fix it. It's all Okey in my host.
